cube_pointer_controller:
  ros__parameters:

    # Joint-space “home” pose for your UR3 (radians)
    # order: shoulder_pan, shoulder_lift, elbow, wrist_1, wrist_2, wrist_3
    home_joint_values: [0.0, -1.57, 1.57, 0.0, 1.57, 0.0]

    # Max velocity & acceleration scaling (0.0–1.0)
    velocity_scaling:      0.30
    acceleration_scaling:  0.30

    # Re-plan thresholds
    replan_threshold_xyz:  0.02     # metres

    # Mock cubes configuration
    mock_cubes_xy:     [0.30,  0.10,
                        0.35, -0.12,
                        0.25,  0.18]

    z_offset:          0.10          # tool-tip 10 cm above table
