cube_pointer_controller:
  ros__parameters:

    # Joint-space “home” pose for your UR3 (radians)
    # order: shoulder_pan, shoulder_lift, elbow, wrist_1, wrist_2, wrist_3
    home_joint_values: [-1.57,-1.57, 0.0, -1.57, 0.0, 0.0]

    # Re-plan thresholds
    replan_threshold_xyz:  0.02     # metres

    z_offset:          0.20          # tool-tip 10 cm above table
